import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/app-header";
import { MUIThemeProvider } from "@/components/providers/mui-theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MUIThemeProvider>
          <div className="mx-auto max-w-5xl px-4 py-6">
            {/* 全局头部（展示登录状态与导航） */}
            <AppHeader />
            {children}
          </div>
        </MUIThemeProvider>
      </body>
    </html>
  );
}
