import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/app-header";
import { MUIThemeProvider } from "@/components/providers/mui-theme-provider";
import { PageTransition } from "@/components/providers/page-transition";
import { EmotionCacheProvider } from "@/components/providers/emotion-cache";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="zh-CN">
      <head>
        <meta name="emotion-insertion-point" content="" />
      </head>
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <EmotionCacheProvider>
          <MUIThemeProvider>
            <div className="mx-auto max-w-6xl px-4 py-6">
              <AppHeader />
              <PageTransition>{children}</PageTransition>
            </div>
          </MUIThemeProvider>
        </EmotionCacheProvider>
          </body>
      </html>
  );
}
